[build]
  publish = "."
  command = ""

[context.production.environment]
  SUPABASE_URL = "NETLIFY_ENV_PLACEHOLDER"
  SUPABASE_KEY = "NETLIFY_ENV_PLACEHOLDER"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200